version: 0.2

phases:
  install:
    commands:
      - apt update -qq
      - apt install python3-pip -y -qq
      - pip install pipenv --quiet
      - pipenv sync --dev
      - pipenv shell
  build:
    commands:
      # run pytest
      - pytest -v --disable-pytest-warnings --cov=job_scraper
