version: 0.2

phases:
  install:
    commands:
      - apt update -qq
      - apt install python3-pip -y -qq
      - pip install poetry --quiet
      - poetry install
  build:
    commands:
      # run pytest
      - poetry run pytest -v --disable-pytest-warnings --cov=job_scraper
