version: 0.2

phases:
  install:
    commands:
      - npm install --no-progress -g npm --silent
      - npm install --no-progress -g serverless@1.79.0 --silent
      - npm install --save-dev serverless-python-requirements --silent
      - npm install --save-dev serverless-iam-roles-per-function --silent
      - apt update -qq
      - apt install python3-pip -y -qq
  build:
    commands:
      - mkdir -p target/stg
      - serverless package --package target/stg --stage stg -v -r us-east-1
artifacts:
  files:
    - target/**/*
    - serverless.yml
    - buildspec-deploy.yml
