version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - npm -v
      - node -v
      - npm install --no-progress -g serverless@3.35.2 --silent
      - npm install --save-dev serverless-python-requirements --silent
      - npm install --save-dev serverless-iam-roles-per-function --silent
      - apt update -qq
      - apt install python3-pip -y -qq
      - pip install poetry --quiet
  build:
    commands:
      - which python
      - python --version
      - poetry export --without-hashes -f requirements.txt -o requirements.txt --with-credentials
      - mkdir -p target/stg
      - serverless package --package target/stg --stage stg -r us-east-1 --verbose
artifacts:
  files:
    - target/**/*
    - serverless.yml
    - buildspec-deploy.yml
